---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    opkssh_selinux_home: false
    opkssh_selinux_squid: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
