changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: ---
      labels: []
    - title: 🎉 New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: ---
      labels: []
    - title: 🐛 Bug fixes
      labels:
        - bug
    - title: ---
      labels: []
    - title: Other Changes
      labels:
        - "*"
