- name: Set binary name based on architecture
  ansible.builtin.set_fact:
    opkssh_binary_arch: >-
      {{
        'amd64' if ansible_architecture == 'x86_64'
        else 'arm64' if ansible_architecture == 'aarch64'
        else 'unsupported'
      }}

- name: Fail if unsupported architecture
  ansible.builtin.fail:
    msg: "Unsupported architecture: {{ ansible_architecture }}"
  when: opkssh_binary_arch == 'unsupported'

- name: Set opkssh download base URL
  ansible.builtin.set_fact:
    opkssh_download_base_url: >-
      https://github.com/{{ opkssh_github_repo }}/releases{{ '/latest/download/' if version_installed == 'latest' else '/download/' ~ version_installed ~ '/' }}

- name: Download checksum list
  ansible.builtin.uri:
    url: "{{ opkssh_download_base_url }}checksums.txt"
    return_content: true
  register: checksums_txt

- name: Find the checksums line for opkssh binary
  ansible.builtin.set_fact:
    opkssh_checksum_line: >-
      {{
        checksums_txt.content.splitlines()
        | select('search', "opkssh-linux-" ~ opkssh_binary_arch)
        | list
        | default([])
        | first | default('')
      }}

- name: Extract SHA256 hash from the matched checksum line
  ansible.builtin.set_fact:
    opkssh_sha256: "{{ opkssh_checksum_line | regex_search('^([0-9a-f]{64})', '\\1') }}"

- name: "Download opkssh {{ version_installed }}"
  ansible.builtin.get_url:
    url: "{{ opkssh_download_base_url }}opkssh-linux-{{ opkssh_binary_arch }}"
    dest: "{{ opkssh_install_path }}/{{ opkssh_binary_name }}"
    owner: root
    group: root
    mode: "0755"
    checksum: "sha256:{{ opkssh_sha256 }}"
  notify: Restore SELinux context for opkssh
