---
- name: Fail if opkssh_version is not 'latest' and is lower than v0.9.0
  ansible.builtin.fail:
    msg: "opkssh_version must be 'latest' or >= v0.9.0 (current: {{ opkssh_version }})"
  when:
    - opkssh_version != 'latest'
    - (opkssh_version | regex_replace('^v', '')) is version('0.9.0', '<', version_type='semver')

- name: Get latest release info from GitHub API
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ opkssh_github_repo }}/releases/latest"
    return_content: true
  register: release_info
  when: opkssh_version == "latest"

- name: Set opkssh version installed
  ansible.builtin.set_fact:
    version_installed: >-
      {{ release_info.json.tag_name if opkssh_version == "latest" else opkssh_version }}

- name: Install opkssh binary
  ansible.builtin.include_tasks:
    file: client.yml

- name: Create opkssh group
  ansible.builtin.group:
    name: "{{ opkssh_group }}"
    state: present

- name: Create opkssh user
  ansible.builtin.user:
    name: "{{ opkssh_user }}"
    state: present
    shell: /sbin/nologin
    system: true
    create_home: false
    group: "{{ opkssh_group }}"

- name: Configure SELinux
  ansible.builtin.include_tasks:
    file: selinux.yml
  when:
    - ansible_selinux is defined
    - ansible_selinux.status not in ['disabled', 'Missing selinux Python library']

- name: Create opkssh configuration directory
  ansible.builtin.file:
    name: /etc/opk
    state: directory
    owner: root
    group: "{{ opkssh_group }}"
    mode: "0750"

- name: Create opkssh policy directory
  ansible.builtin.file:
    name: /etc/opk/policy.d
    state: directory
    owner: root
    group: "{{ opkssh_group }}"
    mode: "0750"

- name: Create opkssh providers file
  ansible.builtin.template:
    src: providers
    dest: /etc/opk/providers
    owner: root
    group: "{{ opkssh_group }}"
    mode: '0640'

- name: Create opkssh config.yml file
  ansible.builtin.template:
    src: config.yml
    dest: /etc/opk/config.yml
    owner: root
    group: "{{ opkssh_group }}"
    mode: '0640'

- name: Create the auth_id file for opkssh
  ansible.builtin.template:
    src: auth_id
    dest: /etc/opk/auth_id
    owner: root
    group: "{{ opkssh_group }}"
    mode: "0640"

- name: Configure openSSH Server
  ansible.builtin.template:
    src: 60-opk-ssh.conf
    dest: "/etc/ssh/sshd_config.d/{{ opkssh_ssh_config_filename }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart openSSH Server

- name: Add sudoers file for opkssh
  ansible.builtin.template:
    src: sudoers.opkssh
    dest: "{{ opkssh_sudoers_path }}/opkssh"
    owner: root
    group: root
    mode: "0440"
  when: opkssh_selinux_home
