---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Uninstall using opkssh absent tasks
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        tasks_from: absent
