---
- name: Restart openSSH Server
  ansible.builtin.service:
    name: "{{ openssh_service_name }}"
    state: restarted
  when: opkssh_restart_ssh

- name: Install SELinux module
  ansible.builtin.copy:
    src: "{{ tefile }}"
    dest: "{{ te_tmp }}"
    owner: root
    group: root
    mode: "0640"
  notify: Compile SELinux module

- name: Compile SELinux module
  ansible.builtin.command:
    argv:
      - checkmodule
      - -M
      - -m
      - -o
      - "{{ mod_tmp }}"
      - "{{ te_tmp }}"
  notify: Packaging SELinux module
  changed_when: true

- name: Packaging SELinux module
  ansible.builtin.command:
    argv:
      - semodule_package
      - -o
      - "{{ pp_tmp }}"
      - -m
      - "{{ mod_tmp }}"
  notify: Install module
  changed_when: true

- name: Install module
  ansible.builtin.command:
    argv:
      - semodule
      - -i
      - "{{ pp_tmp }}"
  notify: Remove temporary files
  changed_when: true

- name: Remove temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ te_tmp }}"
    - "{{ mod_tmp }}"
    - "{{ pp_tmp }}"

- name: Remove SELinux module
  ansible.builtin.command:
    argv:
      - semodule
      - -r
      - "{{ semodule_name }}"
  changed_when: true
