---
- name: Restart openSSH Server
  ansible.builtin.service:
    name: "{{ openssh_service_name }}"
    state: restarted
  when: opkssh_restart_ssh

- name: Restore SELinux context for opkssh
  ansible.builtin.command: "restorecon {{ opkssh_install_path }}/{{ opkssh_binary_name }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux.status not in ['disabled', 'Missing selinux Python library']
  changed_when: true

- name: Compile SELinux module
  ansible.builtin.command:
    argv:
      - checkmodule
      - -M
      - -m
      - -o
      - "/tmp/opkssh.mod"
      - "/usr/share/opkssh/opkssh.te"
  notify: Packaging SELinux module
  changed_when: true

- name: Packaging SELinux module
  ansible.builtin.command:
    argv:
      - semodule_package
      - -o
      - "/tmp/opkssh.pp"
      - -m
      - "/tmp/opkssh.mod"
  notify: Install module
  changed_when: true

- name: Install module
  ansible.builtin.command:
    argv:
      - semodule
      - -i
      - "/tmp/opkssh.pp"
  notify: Remove temporary files
  changed_when: true

- name: Remove temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/opkssh.mod"
    - "/tmp/opkssh.pp"

- name: Remove SELinux module
  ansible.builtin.command:
    argv:
      - semodule
      - -r
      - "{{ semodule_name }}"
  changed_when: true
